
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
  labels:
    app: aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::{aws_account}:role/{aws-s3-role}
spec:
  containers:
  - image: sscalzadonna/aws-cli:1.0
    command:
      - "aws"
      - "s3"
      - "ls"
      - "{bucket-name}"
    name: aws-cli
  restartPolicy: Never
  terminationGracePeriodSeconds: 3